### ISSUE TITLE
Pobieranie imienia użytkownika.

### ISSUE THREAD

**Issue by DariuSz93** [DariuSz93/hello-world#3]
Warto zastanowić się nad dodaniem możliwości podania swojego imienia w pliku hello.cpp. Dzięki temu będziemy mogli powitać bezpośrednio każdego z użytkowników naszego programu. :smiley: @wolny94 Co o tym sądzisz?

**Comment by wolny94** [comment]
DariuSz93 Fajny pomysł, ale miej na uwadze to, że nie każdy chce z naszym programem przechodzić na "Ty", dlatego musielibyśmy jeszcze dodać opcję, gdzie użytkownik może zaznaczyć, czy przeszedł z programem na "Ty".

**Comment by DariuSz93** [comment]
@wolny94 Masz rację, zajmij się tym. :+1:

**Comment by wolny94** [comment]
@DariuSz93 Twój pomysł, twoja działka.

**Comment by DariuSz93** [comment]
@wolny94 Owszem, ale możesz się chyba tym zająć, czyż nie?

**Comment by wolny94** [comment]
@DariuSz93 Ok, to Ty z Mariuszem zajmij się bazą danych.

**Comment by DariuSz93** [comment]
@wolny94 Baza danych już działa.

**Comment by wolny94** [comment]
@DariuSz93 Mariusz wspominał coś o problemie z bazą przy zawijaniu tekstu.

**Comment by DariuSz93** [comment]
@wolny94 Dodałem deadline dla tej funkcjonalności. Liczę, że wyrobisz się na czas. :smile:

**Comment by DariuSz93** [comment]
@wolny94 Załatwione. :stuck_out_tongue:
